#	Created automatically by 'configure'
#

#
#	Compile flags
#
CLIPROOT='/home/tavinus/cliproot'
include /home/tavinus/cliproot/include/Makefile.inc
OSNAME='LINUX'
DLLSUFF='.so'
DLLREALSUFF='.so'
INCLUDEDIRS=-I. -I./fwin -I$(CLIPROOT)/include -I../clip-cti/include -I../clip-gtk

